# Generated by Django 3.1.6 on 2021-06-20 12:05

from django.db import migrations

import json


def add_countries(apps, schema_editor):
    region = apps.get_model('main', 'Region')

    with open('./apps/main/countries.json') as json_file:
        data = json.load(json_file)
        for country in data:
            region.objects.create(
                name=country['name'],
                code=country['code'],
                phone_number_code=country['phone_code'],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210426_1345'),
    ]

    operations = [
        migrations.RunPython(add_countries),
    ]
