SMS_SERVICE_ACCOUNT_SID = env.str('TWILIO_ACCOUNT_SID', default=None)
SMS_SERVICE_AUTH_TOKEN = env.str('TWILIO_AUTH_TOKEN', default=None)
SMS_SERVICE_FROM_SMS = env.str('TWILIO_FROM_NUMBER', default=None)
SMS_SERVICE_CHAT_PHONE_NUMBER = env.str('TWILIO_CHAT_PHONE_NUMBER', default=None)
SMS_SERVICE_MAX_ATTEMPTS = env.int('SMS_SERVICE_MAX_ATTEMPTS', default=5)
SMS_SERVICE_DEBUG = env.bool('SMS_SERVICE_DEBUG', default=False)
SMS_SERVICE_WEBHOOK_SECRET = env.str('TWILIO_WEBHOOK_SECRET', default=None)
SMS_CHAT_DEBUG = env.bool('TWILIO_CHAT_DEBUG', default=False)
SMS_DEBUG_CODE = 1111
